---
abstract: 'IANA Character Set Registry names and Unicode::MapUTF8'
author:
  - 'Martin Thurn, C<mthurn@cpan.org>, L<http://tinyurl.com/nn67z>.'
build_requires:
  IO::Capture::Stderr: 0
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: I18N-Charset
no_index:
  directory:
    - inc
    - t
recommends:
  App::Info::Lib::Iconv: 0
  Encode: 0
  Jcode: 0
  Unicode::Map: 0
  Unicode::Map8: 0
  Unicode::MapUTF8: 0
requires:
  IO::String: 0
  perl: 5.004
version: 1.394
