---
abstract: 'IANA Character Set Registry names and Unicode::MapUTF8'
author:
  - "Martin 'Kingpin' Thurn, C<mthurn at cpan.org>, L<http://tinyurl.com/nn67z>."
build_requires:
  ExtUtils::MakeMaker: 6.36
  IO::Capture::Stderr: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: I18N::Charset
name: I18N-Charset
no_index:
  directory:
    - inc
    - t
recommends:
  App::Info::Lib::Iconv: 0
  Encode: 0
  Jcode: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Unicode::Map: 0
  Unicode::Map8: 0
  Unicode::MapUTF8: 0
requires:
  perl: 5.004
resources:
  license: http://dev.perl.org/licenses/
version: 1.412
