author: Martin Thurn <mthurn@cpan.org>
build_requires: 
  IO::Capture::Stderr: 0
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: I18N-Charset
no_index: 
  directory: 
    - inc
    - t
recommends: 
  App::Info::Lib::Iconv: 0
  Encode: 0
  Unicode::Map: 0
  Unicode::Map8: 0
  Unicode::MapUTF8: 0
requires: 
  IO::String: 0
  perl: 5.004
version: 1.382
